title: "printf"
description: thoughts on software
show_downloads: false
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://neilmacmullen.github.io/" # the base hostname & protocol for your site
twitter_username: NeilMacMullen
github_username:  MacmullenNeil
google_analytics: "G-CMFCNKTJQF"
# Build settings
markdown: kramdown
theme: jekyll-theme-tactile
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: enable_coderay